# -*- coding: utf-8 -*-
"""Streamlit

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FyUekIrIQcZ3U5FXn0QZPZ740jPdBy-0
"""

import joblib
import streamlit as st
import joblib
import numpy as np
import pandas as pd

# Load your trained model
model = joblib.load("mortality_model.pkl")

st.title("🩸 Traumatic Injury Mortality Risk Predictor")
st.write("Enter patient lab results to predict mortality risk (0 = Survived, 1 = Died).")

# Feature names (must match the training order)
feature_names = [
    "ISS", "Maximum Stiffness (Pa)", "Clotting Rate (Pa/s)",
    "D-dimer", "Fibrinogen Concentration", "Velocity Index",
    "PTT", "SBP",  "DBP", "GCS"
]

user_input = []
for feature in feature_names:
    value = st.number_input(f"{feature}:", value=0.0, format="%.2f")
    user_input.append(value)

if st.button("Predict"):
    input_array = np.array([user_input])  # shape (1, 10)
    prediction = model.predict(input_array)[0]
    probability = model.predict_proba(input_array)[0][1]  # prob of death

    st.subheader("🧾 Result:")
    st.write(f"**Prediction**: {'☠️ Died (1)' if prediction else '💚 Survived (0)'}")
    st.write(f"**Probability of Death**: {probability:.2%}")